items:
  - uid: ApplicationOperations~ApplicationOperations
    id: ApplicationOperations
    parent: ApplicationOperations
    name: ApplicationOperations
    type: Class
    syntax:
      content: ApplicationOperations
    fullName: ApplicationOperations.ApplicationOperations
    children:
      - 'ApplicationOperations~ApplicationOperations#client'
      - 'ApplicationOperations~ApplicationOperations#create'
      - 'ApplicationOperations~ApplicationOperations#deleteMethod'
      - 'ApplicationOperations~ApplicationOperations#get'
      - 'ApplicationOperations~ApplicationOperations#list'
      - 'ApplicationOperations~ApplicationOperations#update'
  - uid: 'ApplicationOperations~ApplicationOperations#client'
    id: client
    parent: ApplicationOperations~ApplicationOperations
    name: client
    type: Field
    syntax:
      content: client
    fullName: ApplicationOperations~ApplicationOperations.client
  - uid: 'ApplicationOperations~ApplicationOperations#create'
    id: create
    parent: ApplicationOperations~ApplicationOperations
    name: >-
      create(parameters, parameters.availableToOtherTenants,
      parameters.displayName, parameters.homepage, parameters.identifierUris,
      parameters.replyUrls, parameters.keyCredentials,
      parameters.passwordCredentials, callback)
    summary: "Create a new application.  (see\rhttp://msdn.microsoft.com/en-us/library/azure/hh974476.aspx for more\rinformation)"
    type: Method
    syntax:
      parameters:
        - id: parameters
          type: ApplicationCreateParameters
          description: "Parameters to create an\rapplication."
        - id: parameters.availableToOtherTenants
          type: boolean
          description: "Indicates if the\rapplication will be available to other tenants"
        - id: parameters.displayName
          type: string
          description: Application display name
        - id: parameters.homepage
          type: string
          description: Application homepage
        - id: parameters.identifierUris
          type: IEnumerable
          description: Application Uris
        - id: parameters.replyUrls
          type: IEnumerable
          description: Application reply Urls
        - id: parameters.keyCredentials
          type: IEnumerable
          description: "Gets or sets the list of\rKeyCredential objects"
        - id: parameters.passwordCredentials
          type: IEnumerable
          description: "Gets or sets the\rlist of PasswordCredential objects"
        - id: callback
          type: function
      return:
        type: Stream
        description: The response stream.
      content: >-
        function create(parameters, parameters.availableToOtherTenants,
        parameters.displayName, parameters.homepage, parameters.identifierUris,
        parameters.replyUrls, parameters.keyCredentials,
        parameters.passwordCredentials, callback);
    fullName: >-
      ApplicationOperations~ApplicationOperations.create(parameters,
      parameters.availableToOtherTenants, parameters.displayName,
      parameters.homepage, parameters.identifierUris, parameters.replyUrls,
      parameters.keyCredentials, parameters.passwordCredentials, callback)
    children:
      - 'ApplicationOperations~ApplicationOperations#create~url2'
      - 'ApplicationOperations~ApplicationOperations#create~url2'
      - 'ApplicationOperations~ApplicationOperations#create~url2'
      - 'ApplicationOperations~ApplicationOperations#create~url2'
      - 'ApplicationOperations~ApplicationOperations#create~queryParameters'
      - 'ApplicationOperations~ApplicationOperations#create~url2'
      - 'ApplicationOperations~ApplicationOperations#create~baseUrl'
      - 'ApplicationOperations~ApplicationOperations#create~baseUrl'
      - 'ApplicationOperations~ApplicationOperations#create~url2'
      - 'ApplicationOperations~ApplicationOperations#create~url2'
      - 'ApplicationOperations~ApplicationOperations#create~url2'
      - 'ApplicationOperations~ApplicationOperations#create~httpRequest'
      - 'ApplicationOperations~ApplicationOperations#create~requestContent'
      - 'ApplicationOperations~ApplicationOperations#create~requestDoc'
      - >-
        ApplicationOperations~ApplicationOperations#create~applicationCreateParametersValue
      - 'ApplicationOperations~ApplicationOperations#create~requestDoc'
      - 'ApplicationOperations~ApplicationOperations#create~identifierUrisArray'
      - 'ApplicationOperations~ApplicationOperations#create~loweredIndex1'
      - 'ApplicationOperations~ApplicationOperations#create~loweredIndex1'
      - 'ApplicationOperations~ApplicationOperations#create~identifierUrisItem'
      - 'ApplicationOperations~ApplicationOperations#create~replyUrlsArray'
      - 'ApplicationOperations~ApplicationOperations#create~loweredIndex2'
      - 'ApplicationOperations~ApplicationOperations#create~loweredIndex2'
      - 'ApplicationOperations~ApplicationOperations#create~replyUrlsItem'
      - 'ApplicationOperations~ApplicationOperations#create~keyCredentialsArray'
      - 'ApplicationOperations~ApplicationOperations#create~loweredIndex3'
      - 'ApplicationOperations~ApplicationOperations#create~loweredIndex3'
      - 'ApplicationOperations~ApplicationOperations#create~keyCredentialsItem'
      - 'ApplicationOperations~ApplicationOperations#create~keyCredentialValue'
      - >-
        ApplicationOperations~ApplicationOperations#create~passwordCredentialsArray
      - 'ApplicationOperations~ApplicationOperations#create~loweredIndex4'
      - 'ApplicationOperations~ApplicationOperations#create~loweredIndex4'
      - >-
        ApplicationOperations~ApplicationOperations#create~passwordCredentialsItem
      - >-
        ApplicationOperations~ApplicationOperations#create~passwordCredentialValue
      - 'ApplicationOperations~ApplicationOperations#create~requestContent'
  - uid: 'ApplicationOperations~ApplicationOperations#deleteMethod'
    id: deleteMethod
    parent: ApplicationOperations~ApplicationOperations
    name: 'deleteMethod(applicationObjectId, callback)'
    summary: "Delete an application.  (see\rhttp://msdn.microsoft.com/en-us/library/azure/hh974476.aspx for more\rinformation)"
    type: Method
    syntax:
      parameters:
        - id: applicationObjectId
          type: string
          description: Application object id
        - id: callback
          type: function
      return:
        type: Stream
        description: The response stream.
      content: 'function deleteMethod(applicationObjectId, callback);'
    fullName: >-
      ApplicationOperations~ApplicationOperations.deleteMethod(applicationObjectId,
      callback)
    children:
      - 'ApplicationOperations~ApplicationOperations#deleteMethod~url2'
      - 'ApplicationOperations~ApplicationOperations#deleteMethod~url2'
      - 'ApplicationOperations~ApplicationOperations#deleteMethod~url2'
      - 'ApplicationOperations~ApplicationOperations#deleteMethod~url2'
      - 'ApplicationOperations~ApplicationOperations#deleteMethod~url2'
      - 'ApplicationOperations~ApplicationOperations#deleteMethod~queryParameters'
      - 'ApplicationOperations~ApplicationOperations#deleteMethod~url2'
      - 'ApplicationOperations~ApplicationOperations#deleteMethod~baseUrl'
      - 'ApplicationOperations~ApplicationOperations#deleteMethod~baseUrl'
      - 'ApplicationOperations~ApplicationOperations#deleteMethod~url2'
      - 'ApplicationOperations~ApplicationOperations#deleteMethod~url2'
      - 'ApplicationOperations~ApplicationOperations#deleteMethod~url2'
      - 'ApplicationOperations~ApplicationOperations#deleteMethod~httpRequest'
  - uid: 'ApplicationOperations~ApplicationOperations#get'
    id: get
    parent: ApplicationOperations~ApplicationOperations
    name: 'get(applicationObjectId, callback)'
    summary: "Get an application by object Id.  (see\rhttp://msdn.microsoft.com/en-us/library/azure/hh974476.aspx for more\rinformation)"
    type: Method
    syntax:
      parameters:
        - id: applicationObjectId
          type: string
          description: Application object id
        - id: callback
          type: function
      return:
        type: Stream
        description: The response stream.
      content: 'function get(applicationObjectId, callback);'
    fullName: >-
      ApplicationOperations~ApplicationOperations.get(applicationObjectId,
      callback)
    children:
      - 'ApplicationOperations~ApplicationOperations#get~url2'
      - 'ApplicationOperations~ApplicationOperations#get~url2'
      - 'ApplicationOperations~ApplicationOperations#get~url2'
      - 'ApplicationOperations~ApplicationOperations#get~url2'
      - 'ApplicationOperations~ApplicationOperations#get~url2'
      - 'ApplicationOperations~ApplicationOperations#get~queryParameters'
      - 'ApplicationOperations~ApplicationOperations#get~url2'
      - 'ApplicationOperations~ApplicationOperations#get~baseUrl'
      - 'ApplicationOperations~ApplicationOperations#get~baseUrl'
      - 'ApplicationOperations~ApplicationOperations#get~url2'
      - 'ApplicationOperations~ApplicationOperations#get~url2'
      - 'ApplicationOperations~ApplicationOperations#get~url2'
      - 'ApplicationOperations~ApplicationOperations#get~httpRequest'
  - uid: 'ApplicationOperations~ApplicationOperations#list'
    id: list
    parent: ApplicationOperations~ApplicationOperations
    name: >-
      list(parameters, parameters.appId, parameters.displayNameStartsWith,
      parameters.identifierUri, callback)
    summary: "Get applications by filters.  (see\rhttp://msdn.microsoft.com/en-us/library/azure/hh974476.aspx for more\rinformation)"
    type: Method
    syntax:
      parameters:
        - id: parameters
          type: ApplicationFilterParameters
          description: "Application filter\rparameters"
        - id: parameters.appId
          type: Guid
          description: "Returns an application with a specific\rappId."
        - id: parameters.displayNameStartsWith
          type: string
          description: "Returns all\rapplications starting with this displayName."
        - id: parameters.identifierUri
          type: string
          description: "Returns an application which\rcontains the mentioned identifierUri."
        - id: callback
          type: function
      return:
        type: Stream
        description: The response stream.
      content: >-
        function list(parameters, parameters.appId,
        parameters.displayNameStartsWith, parameters.identifierUri, callback);
    fullName: >-
      ApplicationOperations~ApplicationOperations.list(parameters,
      parameters.appId, parameters.displayNameStartsWith,
      parameters.identifierUri, callback)
    children:
      - 'ApplicationOperations~ApplicationOperations#list~url2'
      - 'ApplicationOperations~ApplicationOperations#list~url2'
      - 'ApplicationOperations~ApplicationOperations#list~url2'
      - 'ApplicationOperations~ApplicationOperations#list~url2'
      - 'ApplicationOperations~ApplicationOperations#list~queryParameters'
      - 'ApplicationOperations~ApplicationOperations#list~odataFilter'
      - 'ApplicationOperations~ApplicationOperations#list~odataFilter2'
      - 'ApplicationOperations~ApplicationOperations#list~odataFilter3'
      - 'ApplicationOperations~ApplicationOperations#list~url2'
      - 'ApplicationOperations~ApplicationOperations#list~baseUrl'
      - 'ApplicationOperations~ApplicationOperations#list~baseUrl'
      - 'ApplicationOperations~ApplicationOperations#list~url2'
      - 'ApplicationOperations~ApplicationOperations#list~url2'
      - 'ApplicationOperations~ApplicationOperations#list~url2'
      - 'ApplicationOperations~ApplicationOperations#list~httpRequest'
  - uid: 'ApplicationOperations~ApplicationOperations#update'
    id: update
    parent: ApplicationOperations~ApplicationOperations
    name: >-
      update(applicationObjectId, parameters,
      parameters.availableToOtherTenants, parameters.displayName,
      parameters.homepage, parameters.identifierUris, parameters.replyUrls,
      parameters.keyCredentials, parameters.passwordCredentials, callback)
    summary: "Update existing application.  (see\rhttp://msdn.microsoft.com/en-us/library/azure/hh974476.aspx for more\rinformation)"
    type: Method
    syntax:
      parameters:
        - id: applicationObjectId
          type: string
          description: Application object id
        - id: parameters
          type: ApplicationCreateParameters
          description: "Parameters to create an\rapplication."
        - id: parameters.availableToOtherTenants
          type: boolean
          description: "Indicates if the\rapplication will be available to other tenants"
        - id: parameters.displayName
          type: string
          description: Application display name
        - id: parameters.homepage
          type: string
          description: Application homepage
        - id: parameters.identifierUris
          type: IEnumerable
          description: Application Uris
        - id: parameters.replyUrls
          type: IEnumerable
          description: Application reply Urls
        - id: parameters.keyCredentials
          type: IEnumerable
          description: "Gets or sets the list of\rKeyCredential objects"
        - id: parameters.passwordCredentials
          type: IEnumerable
          description: "Gets or sets the\rlist of PasswordCredential objects"
        - id: callback
          type: function
      return:
        type: Stream
        description: The response stream.
      content: >-
        function update(applicationObjectId, parameters,
        parameters.availableToOtherTenants, parameters.displayName,
        parameters.homepage, parameters.identifierUris, parameters.replyUrls,
        parameters.keyCredentials, parameters.passwordCredentials, callback);
    fullName: >-
      ApplicationOperations~ApplicationOperations.update(applicationObjectId,
      parameters, parameters.availableToOtherTenants, parameters.displayName,
      parameters.homepage, parameters.identifierUris, parameters.replyUrls,
      parameters.keyCredentials, parameters.passwordCredentials, callback)
    children:
      - 'ApplicationOperations~ApplicationOperations#update~url2'
      - 'ApplicationOperations~ApplicationOperations#update~url2'
      - 'ApplicationOperations~ApplicationOperations#update~url2'
      - 'ApplicationOperations~ApplicationOperations#update~url2'
      - 'ApplicationOperations~ApplicationOperations#update~url2'
      - 'ApplicationOperations~ApplicationOperations#update~queryParameters'
      - 'ApplicationOperations~ApplicationOperations#update~url2'
      - 'ApplicationOperations~ApplicationOperations#update~baseUrl'
      - 'ApplicationOperations~ApplicationOperations#update~baseUrl'
      - 'ApplicationOperations~ApplicationOperations#update~url2'
      - 'ApplicationOperations~ApplicationOperations#update~url2'
      - 'ApplicationOperations~ApplicationOperations#update~url2'
      - 'ApplicationOperations~ApplicationOperations#update~httpRequest'
      - 'ApplicationOperations~ApplicationOperations#update~requestContent'
      - 'ApplicationOperations~ApplicationOperations#update~requestDoc'
      - >-
        ApplicationOperations~ApplicationOperations#update~applicationCreateParametersValue
      - 'ApplicationOperations~ApplicationOperations#update~requestDoc'
      - 'ApplicationOperations~ApplicationOperations#update~identifierUrisArray'
      - 'ApplicationOperations~ApplicationOperations#update~loweredIndex1'
      - 'ApplicationOperations~ApplicationOperations#update~loweredIndex1'
      - 'ApplicationOperations~ApplicationOperations#update~identifierUrisItem'
      - 'ApplicationOperations~ApplicationOperations#update~replyUrlsArray'
      - 'ApplicationOperations~ApplicationOperations#update~loweredIndex2'
      - 'ApplicationOperations~ApplicationOperations#update~loweredIndex2'
      - 'ApplicationOperations~ApplicationOperations#update~replyUrlsItem'
      - 'ApplicationOperations~ApplicationOperations#update~keyCredentialsArray'
      - 'ApplicationOperations~ApplicationOperations#update~loweredIndex3'
      - 'ApplicationOperations~ApplicationOperations#update~loweredIndex3'
      - 'ApplicationOperations~ApplicationOperations#update~keyCredentialsItem'
      - 'ApplicationOperations~ApplicationOperations#update~keyCredentialValue'
      - >-
        ApplicationOperations~ApplicationOperations#update~passwordCredentialsArray
      - 'ApplicationOperations~ApplicationOperations#update~loweredIndex4'
      - 'ApplicationOperations~ApplicationOperations#update~loweredIndex4'
      - >-
        ApplicationOperations~ApplicationOperations#update~passwordCredentialsItem
      - >-
        ApplicationOperations~ApplicationOperations#update~passwordCredentialValue
      - 'ApplicationOperations~ApplicationOperations#update~requestContent'
references:
  - uid: ApplicationCreateParameters
    name: ApplicationCreateParameters
    fullName: ApplicationCreateParameters
    isExternal: false
  - uid: boolean
    name: boolean
    fullName: boolean
    isExternal: true
  - uid: string
    name: string
    fullName: string
    isExternal: false
  - uid: IEnumerable
    name: IEnumerable
    fullName: IEnumerable
    isExternal: true
  - uid: function
    name: function
    fullName: function
    isExternal: false
  - uid: Stream
    name: Stream
    fullName: Stream
    isExternal: true
  - uid: ApplicationFilterParameters
    name: ApplicationFilterParameters
    fullName: ApplicationFilterParameters
    isExternal: true
  - uid: Guid
    name: Guid
    fullName: Guid
    isExternal: true
