items:
  - uid: ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations
    id: ServiceDiagnosticSettingsOperations
    parent: ServiceDiagnosticSettingsOperations
    name: ServiceDiagnosticSettingsOperations
    type: Class
    syntax:
      content: ServiceDiagnosticSettingsOperations
    fullName: ServiceDiagnosticSettingsOperations.ServiceDiagnosticSettingsOperations
    children:
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#client
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#deleteMethod
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#get
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put
  - uid: >-
      ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#client
    id: client
    parent: ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations
    name: client
    type: Field
    syntax:
      content: client
    fullName: >-
      ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations.client
  - uid: >-
      ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#deleteMethod
    id: deleteMethod
    parent: ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations
    name: 'deleteMethod(resourceUri, callback)'
    summary: Deletes the diagnostic settings for the specified resource.
    type: Method
    syntax:
      parameters:
        - id: resourceUri
          type: string
          description: The resource identifier of the configuration.
        - id: callback
          type: function
      return:
        type: Stream
        description: The response stream.
      content: 'function deleteMethod(resourceUri, callback);'
    fullName: >-
      ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations.deleteMethod(resourceUri,
      callback)
    children:
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#deleteMethod~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#deleteMethod~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#deleteMethod~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#deleteMethod~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#deleteMethod~queryParameters
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#deleteMethod~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#deleteMethod~baseUrl
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#deleteMethod~baseUrl
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#deleteMethod~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#deleteMethod~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#deleteMethod~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#deleteMethod~httpRequest
  - uid: >-
      ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#get
    id: get
    parent: ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations
    name: 'get(resourceUri, callback)'
    summary: "Gets the active diagnostic settings. To get the diagnostic settings being\rapplied, use GetStatus."
    type: Method
    syntax:
      parameters:
        - id: resourceUri
          type: string
          description: The resource identifier of the configuration.
        - id: callback
          type: function
      return:
        type: Stream
        description: The response stream.
      content: 'function get(resourceUri, callback);'
    fullName: >-
      ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations.get(resourceUri,
      callback)
    children:
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#get~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#get~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#get~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#get~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#get~queryParameters
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#get~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#get~baseUrl
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#get~baseUrl
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#get~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#get~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#get~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#get~httpRequest
  - uid: >-
      ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put
    id: put
    parent: ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations
    name: >-
      put(resourceUri, parameters, parameters.properties,
      parameters.properties.storageAccountId,
      parameters.properties.storageAccountName, parameters.properties.metrics,
      parameters.properties.logs, callback)
    summary: "Create or update new diagnostic settings for the specified resource. This\roperation is long running. Use GetStatus to check the status of this\roperation."
    type: Method
    syntax:
      parameters:
        - id: resourceUri
          type: string
          description: The resource identifier of the configuration.
        - id: parameters
          type: ServiceDiagnosticSettingsPutParameters
          description: "Parameters\rsupplied to the operation."
        - id: parameters.properties
          type: ServiceDiagnosticSettings
          description: "Gets or sets\rthe public configuration settings."
        - id: parameters.properties.storageAccountId
          type: string
          description: "Gets or sets the\rresource id of the storage account."
        - id: parameters.properties.storageAccountName
          type: string
          description: "[Deprecated]\rUse StorageAccountId instead. Gets or sets the name of the storage\raccount."
        - id: parameters.properties.metrics
          type: array
          description: "Gets or sets the list of\rmetrics."
        - id: parameters.properties.logs
          type: array
          description: Gets or sets the list of logs.
        - id: callback
          type: function
      return:
        type: Stream
        description: The response stream.
      content: >-
        function put(resourceUri, parameters, parameters.properties,
        parameters.properties.storageAccountId,
        parameters.properties.storageAccountName, parameters.properties.metrics,
        parameters.properties.logs, callback);
    fullName: >-
      ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations.put(resourceUri,
      parameters, parameters.properties, parameters.properties.storageAccountId,
      parameters.properties.storageAccountName, parameters.properties.metrics,
      parameters.properties.logs, callback)
    children:
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~queryParameters
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~baseUrl
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~baseUrl
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~url2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~httpRequest
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~requestContent
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~requestDoc
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~serviceDiagnosticSettingsPutParametersValue
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~requestDoc
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~propertiesValue
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~metricsArray
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~loweredIndex1
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~loweredIndex1
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~metricsItem
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~metricSettingsValue
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~retentionPolicyValue
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~logsArray
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~loweredIndex2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~loweredIndex2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~logsItem
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~logSettingsValue
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~retentionPolicyValue2
      - >-
        ServiceDiagnosticSettingsOperations~ServiceDiagnosticSettingsOperations#put~requestContent
references:
  - uid: string
    name: string
    fullName: string
    isExternal: false
  - uid: function
    name: function
    fullName: function
    isExternal: false
  - uid: Stream
    name: Stream
    fullName: Stream
    isExternal: true
  - uid: ServiceDiagnosticSettingsPutParameters
    name: ServiceDiagnosticSettingsPutParameters
    fullName: ServiceDiagnosticSettingsPutParameters
    isExternal: true
  - uid: ServiceDiagnosticSettings
    name: ServiceDiagnosticSettings
    fullName: ServiceDiagnosticSettings
    isExternal: true
  - uid: array
    name: array
    fullName: array
    isExternal: true
