items:
  - uid: SettingsOperations~SettingsOperations
    id: SettingsOperations
    parent: SettingsOperations
    name: SettingsOperations
    type: Class
    syntax:
      content: SettingsOperations
    fullName: SettingsOperations.SettingsOperations
    children:
      - 'SettingsOperations~SettingsOperations#client'
      - 'SettingsOperations~SettingsOperations#deleteMethod'
      - 'SettingsOperations~SettingsOperations#get'
      - 'SettingsOperations~SettingsOperations#list'
      - 'SettingsOperations~SettingsOperations#update'
  - uid: 'SettingsOperations~SettingsOperations#client'
    id: client
    parent: SettingsOperations~SettingsOperations
    name: client
    type: Field
    syntax:
      content: client
    fullName: SettingsOperations~SettingsOperations.client
  - uid: 'SettingsOperations~SettingsOperations#deleteMethod'
    id: deleteMethod
    parent: SettingsOperations~SettingsOperations
    name: 'deleteMethod(settingId, callback)'
    summary: Gets a setting.
    type: Method
    syntax:
      parameters:
        - id: settingId
          type: string
          description: The setting identifier.
        - id: callback
          type: function
      return:
        type: Stream
        description: The response stream.
      content: 'function deleteMethod(settingId, callback);'
    fullName: 'SettingsOperations~SettingsOperations.deleteMethod(settingId, callback)'
    children:
      - 'SettingsOperations~SettingsOperations#deleteMethod~url2'
      - 'SettingsOperations~SettingsOperations#deleteMethod~url2'
      - 'SettingsOperations~SettingsOperations#deleteMethod~url2'
      - 'SettingsOperations~SettingsOperations#deleteMethod~baseUrl'
      - 'SettingsOperations~SettingsOperations#deleteMethod~baseUrl'
      - 'SettingsOperations~SettingsOperations#deleteMethod~url2'
      - 'SettingsOperations~SettingsOperations#deleteMethod~url2'
      - 'SettingsOperations~SettingsOperations#deleteMethod~url2'
      - 'SettingsOperations~SettingsOperations#deleteMethod~httpRequest'
  - uid: 'SettingsOperations~SettingsOperations#get'
    id: get
    parent: SettingsOperations~SettingsOperations
    name: 'get(settingId, callback)'
    summary: Gets a setting.
    type: Method
    syntax:
      parameters:
        - id: settingId
          type: string
          description: The setting identifier.
        - id: callback
          type: function
      return:
        type: Stream
        description: The response stream.
      content: 'function get(settingId, callback);'
    fullName: 'SettingsOperations~SettingsOperations.get(settingId, callback)'
    children:
      - 'SettingsOperations~SettingsOperations#get~url2'
      - 'SettingsOperations~SettingsOperations#get~url2'
      - 'SettingsOperations~SettingsOperations#get~url2'
      - 'SettingsOperations~SettingsOperations#get~baseUrl'
      - 'SettingsOperations~SettingsOperations#get~baseUrl'
      - 'SettingsOperations~SettingsOperations#get~url2'
      - 'SettingsOperations~SettingsOperations#get~url2'
      - 'SettingsOperations~SettingsOperations#get~url2'
      - 'SettingsOperations~SettingsOperations#get~httpRequest'
  - uid: 'SettingsOperations~SettingsOperations#list'
    id: list
    parent: SettingsOperations~SettingsOperations
    name: list(callback)
    summary: Lists the settings.
    type: Method
    syntax:
      parameters:
        - id: callback
          type: function
      return:
        type: Stream
        description: The response stream.
      content: function list(callback);
    fullName: SettingsOperations~SettingsOperations.list(callback)
    children:
      - 'SettingsOperations~SettingsOperations#list~url2'
      - 'SettingsOperations~SettingsOperations#list~url2'
      - 'SettingsOperations~SettingsOperations#list~baseUrl'
      - 'SettingsOperations~SettingsOperations#list~baseUrl'
      - 'SettingsOperations~SettingsOperations#list~url2'
      - 'SettingsOperations~SettingsOperations#list~url2'
      - 'SettingsOperations~SettingsOperations#list~url2'
      - 'SettingsOperations~SettingsOperations#list~httpRequest'
  - uid: 'SettingsOperations~SettingsOperations#update'
    id: update
    parent: SettingsOperations~SettingsOperations
    name: 'update(parameters, parameters.settings, callback)'
    summary: Updates a setting.
    type: Method
    syntax:
      parameters:
        - id: parameters
          type: SettingsUpdateParameters
          description: The setting value.
        - id: parameters.settings
          type: object
          description: The setting values.
        - id: callback
          type: function
      return:
        type: Stream
        description: The response stream.
      content: 'function update(parameters, parameters.settings, callback);'
    fullName: >-
      SettingsOperations~SettingsOperations.update(parameters,
      parameters.settings, callback)
    children:
      - 'SettingsOperations~SettingsOperations#update~url2'
      - 'SettingsOperations~SettingsOperations#update~url2'
      - 'SettingsOperations~SettingsOperations#update~baseUrl'
      - 'SettingsOperations~SettingsOperations#update~baseUrl'
      - 'SettingsOperations~SettingsOperations#update~url2'
      - 'SettingsOperations~SettingsOperations#update~url2'
      - 'SettingsOperations~SettingsOperations#update~url2'
      - 'SettingsOperations~SettingsOperations#update~httpRequest'
      - 'SettingsOperations~SettingsOperations#update~requestContent'
      - 'SettingsOperations~SettingsOperations#update~requestDoc'
      - 'SettingsOperations~SettingsOperations#update~settingsDictionary'
      - 'SettingsOperations~SettingsOperations#update~settingsKey'
      - 'SettingsOperations~SettingsOperations#update~settingsValue'
      - 'SettingsOperations~SettingsOperations#update~requestDoc'
      - 'SettingsOperations~SettingsOperations#update~requestContent'
references:
  - uid: string
    name: string
    fullName: string
    isExternal: false
  - uid: function
    name: function
    fullName: function
    isExternal: false
  - uid: Stream
    name: Stream
    fullName: Stream
    isExternal: true
  - uid: SettingsUpdateParameters
    name: SettingsUpdateParameters
    fullName: SettingsUpdateParameters
    isExternal: true
  - uid: object
    name: object
    fullName: object
    isExternal: false
